[server]
host = "0.0.0.0"
port = 8000

[app]
# default mode; can be overridden via ENVIRONMENT env-var or .env
environment   = "production"

# non-sensitive defaults
mongodb_db    = "market_feeling"
gcp_project   = "autoinvestor-tfm"
pubsub_topic  = "market-feeling-events"
pubsub_subscription  = "market-feeling-to-core"
